name: Continuous Deployment

on:
  push:
    branches:
      - rewrite
      # TODO: Change this to 'main' once rewrite is done
    paths:
      - 'apps/**'
      - 'packages/**'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'staging'
        options:
          - 'staging'
          - 'production'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  # build:
  # uses: ./.github/workflows/build.yml

  deploy:
    name: Deploy to ${{ github.event.inputs.environment }}
    # needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Execute remote commands
        uses: appleboy/ssh-action@master
        env:
          PROJECT_DIRECTORY: ${{ secrets.PROJECT_DIRECTORY }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          envs: PROJECT_DIRECTORY
          script: |
            cd $PROJECT_DIRECTORY
            git pull
            npm run prepare-for:${{ github.event.inputs.environment }}
            npm run deploy-to:${{ github.event.inputs.environment }}
            echo "[Workflow] Deployed successfully"
