name: Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'apps/**'
      - 'packages/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/build.yml

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Execute remote commands
        uses: appleboy/ssh-action@master
        env:
          PROJECT_PATH: ${{ secrets.PROJECT_PATH }}
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.HOST_USERNAME }}
          password: ${{ secrets.HOST_PASSWORD }}
          port: ${{ secrets.HOST_PORT }}
          envs: PROJECT_PATH
          script: |
            cd $PROJECT_PATH
            pnpm pull
            pnpm install
            pnpm stop
            pnpm build
            pnpm nginx
            pnpm start
